--  QUESTION 1
--  If set A = {H  I  J  K  L  M} and set B = {L  M  N  O  P}, what set is generated by the [A union B] operation?
-- the set C (a+b) = {H I J K N O P}

-- QUESTION 2
-- If set A = {H  I  J  K  L  M} and set B = {L  M  N  O  P}, what set is generated by the [A union all B] operation?
--  the set C (a+b) = {H I J K L L M M N O P}

-- 3. The 'last_update' column is found in each table and used to track the last time
--  a value in the row was modified. Write a query to SELECT the last_update dates from the 
--  actor, film, and category tables. Use a compound query to EXCLUDE duplicate values.

SELECT * FROM ((
(SELECT "actor", last_update
	FROM actor)
UNION
(SELECT "film", last_update
	FROM film))
UNION 
(SELECT "categ", last_update
	FROM film_category))a
		ORDER BY last_update;
        
-- PROBELM 4
-- Edit the previous query to INCLUDE duplicate dates.
SELECT * FROM ((
(SELECT "actor", last_update
	FROM actor)
UNION ALL
(SELECT "film", last_update
	FROM film))
UNION ALL
(SELECT "categ", last_update
	FROM film_category)) a
		ORDER BY last_update;
        
-- PROBLEM 5
-- Use a compound query to find the first and last names of all actors 
-- and customers whose last name starts with L. Do not use joins in this query.
SELECT * FROM (
(SELECT last_name, first_name
	FROM customer)
UNION ALL
(SELECT last_name, first_name
	FROM actor)) a
		WHERE last_name LIKE "L%";

-- PROBLEM 6
-- Sort the results from the previous query by the last_name column.

SELECT * FROM (
(SELECT last_name, first_name
	FROM customer)
UNION ALL
(SELECT last_name, first_name
	FROM actor)) a
		WHERE last_name LIKE "L%"
        ORDER BY last_name;
